src/emqtt_bench.erl
This is to avoid flooding console with 'connected: xxx' message
before:
```
connected: 1
connected: 2
connected: 3
...
connected: xxx
sent(4000): total=272, rate=272(msg/sec)
```
after:
```
connected: 363
sent(4000): total=272, rate=272(msg/sec)
connected: 454
sent(5000): total=635, rate=363(msg/sec)
```
i.e. the number after `connected: ` is updated without feeding to a new line.
=> Inline print for the connected counter print

README.md, src/emqtt_bench.erl
For: https://github.com/emqx/emqtt-bench/issues/78
=> feat(conn): allows setting the MQTT protocol version

src/emqtt_bench.erl
Fix: https://github.com/emqx/emqtt-bench/issues/81
=> chore: support to OTP 23 compilation

README.md, rebar.config, src/emqtt_bench.erl
Number of clients will be distributed to each IP accordingly.
also bump the max number of clients to 1 M.
=> feat(srcip): support multiple srouce ips

README.md, rebar.config, src/emqtt_bench.erl
For 100k sub clients, this PR can reduce the mem usage from 2.7G to 830M. (-60%).
=> Mem save mode

src/emqtt_bench.erl
- disconnect conn if sub failed
- monitor pub/sub counters
=> perf: improve robustness

.github/workflows/build.yaml, README.md, rebar.config, rebar.config.script, src/emqtt_bench.app.src, src/emqtt_bench.erl
- quicer 0.0.9
- also make QUIC optional
fix #132 #128
=> quicer 0.0.9

.github/workflows/build.yaml, scripts/rename-package.sh, src/emqtt_bench.erl
- add flag to disable dist port, no scary logging at start when run without epmd
- build and upload package` with/without quic support for user who is not able to install libatomic
=> User friendly changes

src/emqtt_bench.erl
- Adds an option to wait for all publisher to have connected before starting traffic.
While it might be a somewhat unreal scenario, one of our earlier [performance reports](https://www.emqx.com/en/resources/emqx-v-4-3-0-ten-million-connections-performance-test-report) describe that the publishers did behave in that manner.  So, it might be an useful switch to have.
- Adds options to set a minimum and maximum wait time for each publisher to wait before starting its publishing loop (uniform distribution).
=> feat: add new waiting options for publishing

src/emqtt_bench.erl
Adds an option to wait for all publisher to have connected before starting traffic.
While it might be a somewhat unreal scenario, one of our earlier [performance reports](https://www.emqx.com/en/resources/emqx-v-4-3-0-ten-million-connections-performance-test-report) describe that the publishers did behave in that manner.  So, it might be an useful switch to have.
=> feat: opt to wait for all publishers to be in place before start publishing

src/emqtt_bench.erl
With only arg '-i' (interval), one could not achieve conn rate > 1000 connections/s because the interval is in ms.
This PR add new arg "-R" to specify the desired connection rate (conns per secs)
- add `-R` for rate control
- new counters for success/fail connection attempts.
- Fix a bug in stats printing. 
- Smart select number of workers.
=> Add support for rate control for 1000+ conns/s

src/emqtt_bench.erl
=> fix: support otp 22

src/emqtt_bench.erl
Add support for `TLS` `ClientHello` `ServerNameIndication`.
=> Support ssl_opts server_name_indication

.github/workflows/build.yaml, Makefile
also
- bump actions versions
- bump OTP version
- bump rebar version
- bump emqx-builder version
=> ci: release macos packages

.github/workflows/build.yaml, .github/workflows/release.yaml, Dockerfile
fixes #237
also updated OTP, Elixir and builder version in workflows
=> fix: update default builder version

src/emqtt_bench.erl
do not perform in-session message resend by default
=> refactor: no message resend by default

src/emqtt_bench.erl
fixes: https://github.com/emqx/emqtt-bench/issues/257
=> fix: get_value -> get_bool

CHANGELOG.md, src/emqtt_bench.erl
- qoe also tracks `conn` and `pub`
- write client qoe info to disklog (--qoelog logfile)
- dump to csv from qoelog file
=> feat: enhanced QualityOfExp reporting

src/emqtt_bench.erl
=> fix: prometheus metrics observation with qoe enabled

CHANGELOG.md, README.md, src/emqtt_bench.erl
short opt `-s` is now for `--size` only, it was shared by `--shortids`
also update README
=> fix short opts `-s`

src/emqtt_bench.erl
```
emqtt_bench pub -t 'topic/%s/%i/%c/%u/%rand_1000' -c 20 -u user1
```
```
topic/183/18/localhost_bench_pub_1888229295_18/user1/961
```
=> feat: support `%rand_N` placeholder for publish topic
