emqx/emqtt-bench

src/emqtt_bench.erl
./emqtt_bench conn -c 50000 -i 50 -h 192.168.1.50 --ifaddr=192.168.1.150
```
** Reason for termination = exit:{disconnected,141,#{}}
** Callback modules = [emqtt]
** Callback mode = state_functions
** Stacktrace =
**  [{gen_statem,loop_state_callback_result,11,
[{file,"gen_statem.erl"},{line,1312}]},
{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
client(43376): EXIT for {disconnected,141,#{}}
=CRASH REPORT==== 4-Nov-2020::13:45:59.346584 ===
crasher:
initial call: emqtt:init/1
pid: <0.13362.0>
registered_name: []
exception exit: {disconnected,141,#{}}
in function  gen_statem:loop_state_callback_result/11 (gen_statem.erl, line 1312)
ancestors: [<0.13361.0>]
message_queue_len: 0
messages: []
links: [<0.13361.0>]
dictionary: [{send_oct,58}]
trap_exit: true
status: running …
```
=> fix(conn): no pingreq is sent when use ./emqtt_bench conn

src/emqtt_bench.erl
Because client id key is different, it is not applied to mqtt connection setting.
Reference
https://github.com/emqx/emqtt#exports
emqtt:start_link(Options)
{clientid, ClientID}
Specify the client identifier. If not given, the client identifier will use the value assigned by the server in MQTT v5 or be automatically generated by internal code in MQTT v3.1/v3.1.1.
=> Modify client id key of MqttOpts

README.md, src/emqtt_bench.erl
add for setting ACL for benchmark.
so, if client id prefix is set, random value is not added.
=> Add client id prefix option

src/emqtt_bench.erl
We can hibernate processes to reduce memory usage, especially when using the `conn` and `sub` commands
=> chore: hibernate processes to save memory consumption

.github/workflows/build.yaml
We are using `emqtt-bench` on Kubernetes to load test our cluster and I think having an available image for `emqtt-bench` can help people to run these types of load tests more easily.
The current configuration builds the image always with the master tag based on the latest commit on the master branch. also, it builds a tagged image whenever you created a tag.
=> Docker Build Pipeline based on GIthub Actions

Makefile, src/emqtt_bench.erl
several fixes:
1. minor: rebar3 build no need to `release` before `tar`
1. minor: the stats printout `sent` and `pub` are mostly identical, now `sent` is removed
1. minor: the 'since uptime' time elapse is formatted as `h:m:s` for better readability
1. feat: added `inflight` option to control the number of inflight messages for QoS 1 and 2
1. bugfix: in case of QoS 1, there are `puback` messages delivered back to the client process,
the messages are never `receive`d, cause high CPU
1. performance: `timer:send_interval/2` is replaced with `erlang:send_after/3`
1. enhancement: now it also tracks publish call overrun in stats printout, so we know a bit more about message latency when e.g. inflight window is full.
=> Better pace control and more

src/emqtt_bench.erl
I believe there should be no need to adjust message publish interval.
now with 50K clients, 1s interval, we can see it stays at 50K messages per second regardless of how many source addrs in use.
=> fix: do not re-calculate publish interval

src/emqtt_bench.erl
If an atom is supplied as the reason code, `emqtt:disconnect` will
fail to serialize such reason code:
```
=CRASH REPORT==== 15-Dec-2021::11:02:06.695317 ===
crasher:
initial call: emqtt:init/1
pid: <0.193.0>
registered_name: []
exception error: bad argument
in function  iolist_size/1
called as iolist_size([sub_fail,<<0>>])
*** argument 1: not an iodata term
in call from emqtt_frame:serialize/3 (/home/thales/dev/emqx/emqtt/src/emqtt_frame.erl, line 477)
in call from emqtt:send/2 (/home/thales/dev/emqx/emqtt/src/emqtt.erl, line 1331)
in call from emqtt:connected/3 (/home/thales/dev/emqx/emqtt/src/emqtt.erl, line 821)
in call from gen_statem:loop_state_callback/11 (gen_statem.erl, line 1194)
ancestors: [<0.187.0>]
message_queue_len: 0
messages: []
links: [<0.187.0>]
dictionary: [] …
```
=> fix(sub_fail): reason code must be binary

src/emqtt_bench.erl
The bug causes the initial value of the client id to be calculated incorrectly
For example:
```
./emqtt_bench conn -c 10 -k 15 -n 0 --prefix abcd
```
=> fix: fix bad startnumber on multiple addrs

src/emqtt_bench.erl
Even if we change the start number to control the topics and
client_ids, that shouldn't affect the connection count that is
reported to stdout.
=> fix: start count at 1

src/emqtt_bench.erl
Shorter client IDs can lead to a slightly lower memory consumption on
the broker side.  That can be helpful when running with constrained
resources.
=> feat: allow short ids to be used as client ids

src/emqtt_bench.erl
`emqtt:disconnect/2` actually expects a reason code as the second
argument instead of a binary.
https://github.com/emqx/emqtt/blob/8604b50681649a4effa5a78873c9e6ebb66c9e31/src/emqtt.erl#L409
=> fix: return valid reason code when disconnecting

README.md, README_FOR_DOCKER.md
always provide --ssl option when TLS is in use
=> docs: fix readme examples

src/emqtt_bench.erl
this avoids ssl warning in otp24
=> chore: client side ssl verify none

.gitignore, CHANGELOG.md, src/emqtt_bench.erl
The old default value `0` means `infinity`.
Which means no back-pressure from the target MQTT broker under test.
With default set to 1, for each publisher client, only one message
Is put to the send buffer each time.
In conjunction with the `--interval_of_msg` option,
the 'overrun' counter report should indicate if the system
under test is overloaded or not.
=> fix: change --inflight option default value to 1

src/emqtt_bench.erl
This facilitates finding the correct process and distribution port
when using more than one type of bench in the same machine.
=> feat: add mode to distribution name

.gitignore, rebar.config, rebar.config.script, src/emqtt_bench.erl
- Bump quicer to 0.0.16
- Bump emqtt to 1.6.1
- Support subscription QoE measurements
- Store 0-RTT tickets on DETS or Load 0-RTT tickets from DETS
=> quicer performance

Makefile, rebar.config.script
This allow building emqx/emqx-builder#64 successfully under OTP-25 & rebar3 3.19.x.
EMQX-8426
=> chore: allow user to override rebar version

.github/workflows/build.yaml, Dockerfile, rebar.config, rebar.config.script, scripts/rename-package.sh
- actions/checkout@v3 uses sparse checkout by default and rebar fails to detect version correctly
- actions/upload-artifact@v2 fails to detect amazon linux
=> ci: release packages for ubuntu22.04, debian11 and el9

src/emqtt_bench.erl
./bin/emqtt_bench pub --host 116.204.79.214 -p 1883 -t /ys/access/rule/Y000c57ffd9b-1049644423035486208 -c 1 -I 10000 -m $(cat mqtt-p/29-03-2023_16_54_42.60882508.bin)
And the `mqtt-p/29-03-2023_16_54_42.60882508.bin` contains some unicode characters, the emqtt_bench pub fails with the following error:
```
=ERROR REPORT==== 29-Mar-2023::18:24:17.778134 ===
Error in process <0.120.0> with exit value:
{badarg,[{erlang,iolist_to_binary,
[[123,34,20445,25252,67,30456,30005,27969,34,58,123,34,116,
115,34,58,34,49,54,56,48,48,56,48,48,56,50,54,49,48,34,44,
34,118,97,108,117,101,34,58,50,46,54,50,125,44,34,20445,
25252,65,30456,30005,27969,34,58,123,34,116,115,34,58,34,
49,54,56,48,48,56,48,48,56,50,54,49,48,34,44,34,118,97,108,
117,101,34,58,50,46,52,49,125,44,34,39057,29575,34,58,123, …
```
=> fix: badarg error when publish unicode payloads

src/emqtt_bench.erl
when emqtt-bench run with 'conn' command, the default payload_hdrs is unset.
The client may receive pubs due to implicit subscribition
=> fix: default value of payload_hdrs

.github/workflows/build.yaml, .github/workflows/release.yaml
also stop releasing packages for older platforms:
- Ubuntu 16.04
- Ubuntu 18.04
- Debian 9
- Debian 10
- RHEL 7
=> ci: bump actions version

src/emqtt_bench.erl
fixes https://github.com/emqx/emqtt-bench/issues/255
prior to this fix, any last spawn of each chunk triggers the start_pbulishing signal.
this causes slow chunks to monitor a dead process.
=> fix: wait before publish signal should be collected per worker

.github/workflows/release.yaml
if building without quic support
=> ci: do not set BUILD_WITHOUT_QUIC env var in release workflow

rebar.config, rebar.config.script
The quicer app is dynamically added to the escript according to the BUILD_WITHOUT_QUIC Flag, so this must be done in rebar.config.script
=> fix(build): escript_incl_apps in rebar.config.script

src/emqtt_bench.erl
The following command line will ways use `192.168.150.25` as source IP address:
```
./bin/emqtt_bench conn -p 1883 -i 10 -c 50 --ifaddr "192.168.150.25,127.0.0.1"
```
=> fix: ifaddr sharding does not work

rebar.config, rebar.config.script, src/emqtt_bench.erl
This is breaking change:
old `--quic` now must come with `--quic true` as arg type changes.
new  `--quic fine_tune.eterm` is supported for fine tune the quic conn and quic ctrl stream.
=> feat(quic): quic fine tune

Makefile, rebar.config
emqtt 1.13.4 has reconnect fixed
now bench clients should experience less shutdowns when testing with higher connection rate than the target broker allows.
when test against emqx with `max_conn_rate` set to `10`
```
> ./_build/emqtt_bench/rel/emqtt_bench/bin/emqtt_bench conn -h localhost -p 1883 -c 1000 --reconnect 100000
Start with 20 workers, addrs pool size: 1 and req interval: 200 ms
1s connect_succ total=18 rate=17.96/sec
2s connect_succ total=28 rate=10.00/sec
3s connect_succ total=38 rate=10.00/sec
4s connect_succ total=48 rate=10.00/sec
5s connect_succ total=57 rate=9.00/sec
6s connect_succ total=67 rate=10.00/sec
7s connect_succ total=77 rate=10.00/sec
8s connect_succ total=87 rate=10.00/sec
9s connect_succ total=97 rate=10.00/sec
10s connect_succ total=107 rate=10.00/sec
11s …
```
=> fix: upgrade to emqtt 1.13.4

README.md, README_FOR_DOCKER.md, src/emqtt_bench.erl
spelling socoket -> socket fix. 
remove trailing spaces.
=> socoket -> socket

.github/workflows/release.yaml, CHANGELOG.md
quick_support=false caused some troubles: https://github.com/emqx/emqtt-bench/actions/runs/12316275289
=> Always release quic supported version for now

.github/workflows/release.yaml, CHANGELOG.md, rebar.config, src/emqtt_bench.erl
* ~~(Breaking Change) cmdline arg `-S --ssl` now requires one more argument, see below~~
* Support `--ssl-version tlsv1.3` to enforce TLS version. 
* QoE logging now logs TCP handshake latency during TLS handshake ( emqtt 1.14.0).
* QoE logging now logs each publish msg' end to end latency if `--payload-hdrs=ts` is set by both subscriber and publisher. 
* Dump TLS secrets per connecion to SSLKEYLOGFILE specifed by envvar SSLKEYLOGFILE for TLS traffic decryption.  (TLS and QUIC)
* Now build release for arm64.
* Now build release for el7 with newer build image.
=> more functions for QoE tracking

CHANGELOG.md, src/emqtt_bench.erl
`invalid_elapsed` mean n/a value.
we used to present invalid_elapsed to -1 in CSV dump. then the mqtt.publish e2e latency became confusion because in case the test machines(pub machine, sub machine) are not time synced, we could get <0 latency.
Now we present `invalid_elapsed` to "" and should no longer confusion.
=> fix(qoe): csv dump invalid_elapsed to ""

CHANGELOG.md, src/emqtt_bench.erl
add two new opts for TLS tests
--ciphers
--signature_algs
=> feat: support TLS --ciphers and --signature_algs 

CHANGELOG.md, src/emqtt_bench.erl
new opt for Key exchange alg: -keyex-algs
=> feat(tls1.3): new opt for Key exchange alg: `-keyex-algs`

.github/workflows/build.yaml, .github/workflows/release.yaml, src/emqtt_bench.erl
- Fix crash in tcp transport when SSLKEYLOGFILE env is set.
- Remove dummy prepare nst call while handling ssl opts.
=> Fix/william/sslkeylogfile tcp crash 
